version: '3.8'

services:
  # Контейнер для PHP-FPM
  app_fpm:
    image: php:8.2-fpm
    container_name: app_php_fpm
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  # Контейнер для PHP-CLI (для обработки очередей)
  app_cli:
    image: php:8.2-cli
    container_name: app_php_cli
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan", "queue:work"]
    networks:
      - app_network

  # База данных MySQL для Laravel
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: y,K_,1*xkdd?1L
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
