version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/laravel.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_KEY_HERE # Замените YOUR_KEY_HERE сгенерированным ключом
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=gen_user # укажите имя пользователя
      - DB_PASSWORD=:LRc*T<2c,+BRb # укажите пароль

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: gen_user # укажите имя пользователя
      MYSQL_PASSWORD: :LRc*T<2c,+BRb # укажите пароль
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
